In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
training_data= pd.read_csv('C:/Users/Admin/Downloads/training_data.csv')
test_data= pd.read_csv('C:/Users/Admin/Downloads/test_data.csv')

In [3]:
training_data=training_data.set_index([pd.Index(training_data["PatientID"])])

In [4]:
training_data=training_data.drop('PatientID',axis=1)

In [5]:
test_data=test_data.set_index([pd.Index(test_data["PatientID"])])
test_data=test_data.drop('PatientID',axis=1)

In [6]:
training_data['PR Seq'].value_counts()

CCTCAAATCACTCTTTGGCAACGACCCCTCGTCCCAATAAGGATAGGGGGGCAACTAAAGGAAGCYCTATTAGATACAGGAGCAGATGATACAGTATTAGAAGACATGGAGTTGCCAGGAAGATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTAARACAGTATGATCAGRTACCCATAGAAATCTATGGACATAAAGCTGTAGGTACAGTATTAATAGGACCTACACCTGTCAACATAATTGGAAGAAATCTGTTGACTCAGCTTGGTTGCACTTTAAATTTY    1
CCTCAGATCACTCTTTGGCAACGACCCCTCGTCTCAATAAGGGTAGGGGGGCAACTAAAGGAAGCTCTATTAGAYACAGGAGCAGATGATACAGTATTAGAAGARATAGATTTGCCAGGAAGATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTAARACAGTATGATCAGATACCCATAGAAATTTGTGGGCATAAAGCTATAGGTACAGTATTAGTAGGACCTACACCTGTCAACATAATTGGAAGAAATCTGTTGACTCAGATYGGTTGCACTTTAAATTTT    1
CCTCAGATCACTCTTTGGCAACGACCCCTCGTCTCAGTAARGATAGGGGGGCARCTAAAGGAAGCTCTCTTAGAYACAGGAGCAGATGATACAGTRTTAGAAGAMATGAATTTGCCAGGAAGATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTAAGACAGTATGATCAGATACCCATAGAAATCTGTGGACATAAAGCTATAGGTACAGTATTAGTAGGACCTACACCTGTCAACATAATTGGACGAAATCTGTTGACTCAGATTGGYTGCACTTTAAATTTY    1
CCTCAGATCACTCTTTGGCAACGACCCCTCGTCTCARTAARRATAGGAGGGCAAMTCAAGGAAGCTCTATTAGATACAGGAGCAGATGATACAGTATTAGAAGAAATGAATTTGCCAGGAAGATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTRAGACAGTATGATCAGATACCCATAGAAATCTGTGGCCATAAAGCTATAGGTACAGTATTAGTAGGACCTACACCTGTCAACATAATTGGAAGAAATCTGTTGACTCARATTGGTTGCACTTTAAATTTT    1
CCTCAGATCACTCTTTGGCAACGACCCCTCGTCWCAATAAGGRTAGGGGGGCAATCAAAGGAAGCTCTATTAGATACAGGAGCAGATGATACAGTATTAGAAGAAATGAATTTGCCAGGAAAATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTAAGACAGTATGATCAGATACYYRTAGAAATATGTGGACATAAAGCTATAGGTACAGTATTAGTRGGACCTACACCTGTCAACATAATTGGAAGAAATCTGTTGACTCAAATTGGCTGCACTTTAAATTTT    1
                                                                                                                                                                                                                                                                                                            ..
CCTCAGATCACTCTTTGGCAACGACCCCTCGTCACAATAAAGATAGGGGGGCAACTAAAAGAAGCTCTATTAGATACAGGAGCAGATGATACAGTATTAGAAGAAATRAATTTGCCAGGAAGATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTAAGACAGTATGATCAGGTACCCATAGAAATCTGTGGGCATAAAGCTATAGGTACAGTATTAGTAGGACCTACACCTGTCAACATAATTGGAAGAAATCTGTTGACTCAGCTTGGTTGCACTTTAAATTTT    1
CCTCAGATCACTCTTTGGCAACGACCCCTCGTCACAATAAAGATAGGGGGGCAACTAAAGGAAGCTCTATTAGACACAGGAGCAGATGATACAGTATTAGAAGAAATGAATTTGCCAGGAAGATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTAAGACAGTATGATCAGATACTTGTAGAAATCTGTGGACATAAAGCTATAGGTACAGTATTAGTAGGACCTACACCTGTCAACATAATTGGAAGGAACCTGTTGACTCAGATTGGGTGCACTTTAAATTTT    1
CCTCAGATCACTCTTTGGCAACGACCCCTCGTCACAATAAAGATAGGGGGGCAACTAAAGGAAGCTCTATTAGACACAGGAGCAGATGATACAGTATTAGAAGACATRRATTTGCCAGGAAGATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATTAAAGTAARACAGTATGATCAGATACYMATAGAAATCTGTGGACATAAAGCTATAGGTACAGTATTAGTAGGACCTACACCTGTCAACATAATTGGAAGAAATCTGTTGACTCAGATTGGTTGCACTTTAAATTTT    1
CCTCAGATCACTCTTTGGCAACGACCCCTCGTCACAATAAAGATAGGGGGGCAACTAAAGGAAGCTCTATTAGACACAGGGGCAGATGATACAGTATTAGAAGAAATGAGTTTGTCAGGAAGATGGAAACCAAAAATRATAGGGGGAATTGGAGGTTTTATCAAAGTAAGACAGTATGATCAGATACCTGTAGAAATTTGTGGACATAAAGCTATAGGTACAGTATTAATAGGACCTACACCTGTCAACATAATTGGAAGAAATCTGTTGACTCAAATTGGTTGCACTTTAAATTTT    1
TTCGTCACAATAAAGGTAGGGGGGCAACTAATAGAAGCTCTGTTGGATACAGGAGCAGATGATACARTATTAGAAGAAATAAGTTTGCCAGGAAGATGGAAACCAAAAATAATAGGGGGAATTGGAGGTTTTATCAAAGTAAAACAGTATGATCAGATACCCATAGAAATYTGTGGACATAAAGTTGTAGGTACAGTATTAGTAGGACCTACACCTGTCAACATARTTGGAAGAAATCTGATGACTCAGATTGGTTGCACTTTAAATTTT                               1
Name: PR Seq, Length: 920, dtype: int64

In [7]:
training_data[training_data['PR Seq'].isnull()]

,Resp,PR Seq,RT Seq,VL-t0,CD4-t0
PatientID,,,,,
921,0,NaN,GAAATSTGTACAGAAATGSAAAAGGAAGGGAAAATTTCAAAAATTG...,4.10,227
922,0,NaN,AAATTAAAGCCAGGAATGGATGGCCCAAAGGTTAAACAATGGCCAT...,3.20,287
923,0,NaN,AGTCCTATTGAAACTGTACCAGTAAAATTAAAGCCAGGAATGGATG...,3.00,638
924,1,NaN,CCCATAAGTCCTATTGAAACTGTACCAGTAAAATTAAAGCCAGGAA...,4.50,699
925,0,NaN,CCCATAAGTCCTATTGAAACTGTACCAGTAAAATTAAAGCCAGGAA...,2.70,299
...,...,...,...,...,...
996,0,NaN,CCCATTAGTCCTATTGARACTGTACCAGTAMAATTAAAGCCAGGAA...,3.15,354
997,0,NaN,CCCATYAGTCCTATTGAAACTGTACCAGTAAAATTAAAGCCAGGAA...,5.50,50
998,0,NaN,CCCATYAGTCCTATTGAAACTGTACCAGTAAAATTAAAGCCAGGAA...,4.10,369
999,0,NaN,CCTATTAGTCCTATTGAAACTGTACCAGTAAAATTAAAGCCAGGAA...,3.37,127
1000,0,NaN,CCTATTAGTCCTATTGAAACTGTACCTGTAAAATTAAAGCMAGGAA...,4.97,570

In [8]:
training_data=training_data.dropna()

In [9]:
training_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 920 entries, 1 to 920
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Resp    920 non-null    int64
 1   PR Seq  920 non-null    object
 2   RT Seq  920 non-null    object
 3   VL-t0   920 non-null    float64
 4   CD4-t0  920 non-null    int64
dtypes: float64(1), int64(2), object(2)
memory usage: 43.1+ KB

In [10]:
X_train = training_data.drop('Resp',axis=1)
y_train = training_data['Resp']

In [11]:
X_test = test_data.drop('Resp',axis=1)
y_test = test_data['Resp']

In [12]:
y_test.replace('H',1)

PatientID
1      1
2      1
3      1
4      1
5      1
      ..
688    1
689    1
690    1
691    1
692    1
Name: Resp, Length: 692, dtype: int64

In [13]:
PR_train = [-sum([ord(ele)-96 for ele in sub]) for sub in X_train["PR Seq"]]
pr_test = [-sum([ord(ele)-96 for ele in sub]) for sub in X_test["PR Seq"]]

In [14]:
RT_train = [-sum([ord(ele)-96 for ele in sub]) for sub in X_train["RT Seq"]]
RT_test = [-sum([ord(ele)-96 for ele in sub]) for sub in X_test["RT Seq"]]

In [15]:
RT_train

[25262,
 22731,
 22497,
 36732,
 22497,
 22588,
 22482,
 22581,
 22580,
 22523,
 22003,
 36273,
 36308,
 36854,
 22400,
 21584,
 18729,
 22557,
 37011,
 22867,
 18940,
 22536,
 22530,
 18778,
 25197,
 22190,
 36262,
 25139,
 36432,
 22723,
 21670,
 27799,
 24369,
 18665,
 17185,
 22466,
 18772,
 25277,
 22478,
 22510,
 21778,
 36955,
 18730,
 18838,
 25231,
 25221,
 22575,
 37043,
 22835,
 22518,
 18701,
 22617,
 18694,
 24105,
 19366,
 22631,
 22529,
 21368,
 22546,
 19544,
 22296,
 18687,
 22455,
 22691,
 22523,
 22775,
 22538,
 22646,
 22645,
 20897,
 22746,
 24367,
 22445,
 18724,
 22573,
 24348,
 22599,
 25252,
 22732,
 25267,
 18702,
 18705,
 18788,
 22596,
 22815,
 28003,
 21166,
 22636,
 22471,
 22922,
 22512,
 22889,
 22522,
 36737,
 22469,
 22599,
 22071,
 22604,
 36357,
 24144,
 22541,
 20053,
 20233,
 25272,
 22388,
 25028,
 22515,
 22901,
 22116,
 18692,
 22427,
 24312,
 24078,
 22148,
 22582,
 24046,
 25255,
 17378,
 22433,
 18707,
 22578,
 25217,
 24384,
 22745,
 25189,
 22603,
 22523,
 25313,
 22688,
 22482,
 18796,
 22542,
 19677,
 22843,
 24415,
 20235,
 22478,
 22451,
 22384,
 20270,
 36433,
 19463,
 24408,
 18834,
 20174,
 22651,
 19296,
 24364,
 18733,
 36623,
 21912,
 25340,
 22472,
 22786,
 25246,
 25291,
 25045,
 25371,
 22428,
 20392,
 22512,
 22238,
 18783,
 25226,
 22718,
 16902,
 22345,
 22438,
 22622,
 18683,
 22529,
 22660,
 18663,
 22653,
 22670,
 22491,
 22608,
 22457,
 22517,
 18694,
 22690,
 22816,
 18821,
 18775,
 22709,
 22841,
 22575,
 18770,
 22322,
 22597,
 19925,
 21883,
 22880,
 22786,
 22590,
 22671,
 22641,
 22674,
 22534,
 22615,
 22306,
 22668,
 22573,
 20564,
 22610,
 22366,
 22565,
 25280,
 22555,
 22670,
 22725,
 22448,
 19124,
 22320,
 18710,
 22374,
 26019,
 21522,
 22599,
 22492,
 22075,
 25098,
 21128,
 19049,
 14221,
 22824,
 22463,
 25175,
 22688,
 22609,
 21709,
 20922,
 18808,
 22952,
 22580,
 22468,
 22352,
 22558,
 18804,
 22439,
 22672,
 24789,
 18697,
 22622,
 22429,
 21983,
 18017,
 22620,
 22639,
 19247,
 25065,
 36850,
 25254,
 18767,
 22055,
 22322,
 37276,
 22482,
 25270,
 18904,
 20993,
 22631,
 22837,
 27555,
 22557,
 18864,
 22272,
 22415,
 22540,
 22614,
 22691,
 25249,
 25171,
 25257,
 22819,
 25253,
 18778,
 21373,
 21369,
 22419,
 25080,
 22457,
 22596,
 22864,
 36084,
 22619,
 22543,
 22433,
 18701,
 22580,
 22646,
 19080,
 22771,
 26451,
 35810,
 25179,
 21735,
 21544,
 22469,
 25270,
 36449,
 18672,
 22806,
 22414,
 22599,
 36419,
 22611,
 19447,
 22161,
 20274,
 25319,
 25291,
 21276,
 22547,
 19939,
 19426,
 18642,
 19317,
 18801,
 22622,
 22715,
 22096,
 18605,
 23878,
 22451,
 25068,
 18953,
 36568,
 22647,
 22591,
 22292,
 22629,
 22640,
 19666,
 22882,
 18726,
 19456,
 22312,
 22725,
 22491,
 22422,
 19328,
 23871,
 36733,
 18783,
 19758,
 18729,
 22729,
 25561,
 36326,
 20015,
 22427,
 25274,
 36278,
 20201,
 36677,
 36527,
 22094,
 36511,
 22436,
 22530,
 19540,
 18155,
 36547,
 22791,
 20124,
 19412,
 22559,
 22652,
 22611,
 36154,
 18689,
 22341,
 36489,
 36236,
 22554,
 22749,
 22564,
 37163,
 18735,
 18771,
 18725,
 21723,
 17192,
 21552,
 22426,
 22585,
 36145,
 22169,
 19314,
 33837,
 16299,
 22395,
 22733,
 22518,
 22697,
 25295,
 25317,
 22512,
 22630,
 22726,
 22572,
 20269,
 22242,
 22430,
 36575,
 22650,
 22445,
 36704,
 22741,
 18664,
 22611,
 22777,
 36674,
 26521,
 36325,
 36596,
 37006,
 21697,
 22350,
 36883,
 25235,
 22672,
 22672,
 18721,
 36112,
 36789,
 22412,
 36268,
 36070,
 25067,
 25140,
 25207,
 36681,
 18613,
 22458,
 25269,
 21365,
 36284,
 22603,
 36901,
 25203,
 22510,
 36404,
 35066,
 22388,
 25344,
 18815,
 19365,
 36855,
 25322,
 22791,
 24010,
 25242,
 36689,
 18731,
 36813,
 27798,
 36779,
 37121,
 22856,
 22580,
 18817,
 22827,
 22683,
 36623,
 19588,
 21203,
 19300,
 19427,
 18675,
 22531,
 36653,
 36392,
 22587,
 25151,
 22436,
 18688,
 36665,
 22255,
 22361,
 25223,
 21909,
 22703,
 18802,
 24372,
 22491,
 21266,
 36301,
 22543,
 18912,
 25358,
 22686,
 22777,
 14927,
 18858,
 22488,
 36566,
 25186,
 22538,
 24400,
 25352,
 22757,
 22247,
 20362,
 22434,
 22743,
 22604,
 22641,
 22431,
 24286,
 20653,
 22454,
 18865,
 22379,
 22745,
 22403,
 19032,
 22386,
 19507,
 36937,
 35949,
 18631,
 22101,
 22566,
 19408,
 18690,
 20029,
 22692,
 22581,
 22431,
 22829,
 22522,
 22150,
 18575,
 25295,
 22583,
 22549,
 22485,
 36666,
 22407,
 36512,
 22436,
 22301,
 18772,
 22628,
 22537,
 36301,
 25107,
 18643,
 22614,
 25215,
 21849,
 36987,
 36591,
 22569,
 22626,
 22762,
 22061,
 22325,
 22615,
 22289,
 22546,
 18767,
 20671,
 22545,
 22408,
 25360,
 36917,
 36434,
 21865,
 36303,
 19890,
 22555,
 21657,
 36655,
 22346,
 22736,
 23511,
 22777,
 36709,
 36754,
 22568,
 36582,
 22470,
 22564,
 22530,
 25324,
 36801,
 22701,
 37095,
 36728,
 36690,
 22851,
 22657,
 25258,
 22658,
 36698,
 22524,
 36561,
 22681,
 25389,
 17265,
 20159,
 22591,
 36842,
 22381,
 25277,
 36905,
 22505,
 36770,
 18704,
 22178,
 21754,
 22657,
 18730,
 20277,
 36857,
 22551,
 22573,
 22454,
 25218,
 26298,
 22692,
 20615,
 36378,
 36862,
 22729,
 22687,
 22846,
 22483,
 25132,
 22313,
 36476,
 21171,
 22671,
 22450,
 35580,
 18752,
 18712,
 25387,
 22747,
 19260,
 34842,
 22257,
 19519,
 21958,
 21157,
 22516,
 22724,
 18695,
 22515,
 21419,
 19862,
 22501,
 18679,
 18644,
 26238,
 22493,
 19719,
 23595,
 25146,
 19755,
 20381,
 22128,
 22605,
 17956,
 25166,
 36806,
 22515,
 21582,
 25102,
 22430,
 22351,
 36332,
 35180,
 22986,
 22371,
 18792,
 25199,
 36390,
 18721,
 22803,
 22698,
 22253,
 22343,
 36657,
 20905,
 22840,
 25091,
 22634,
 24323,
 18629,
 22395,
 22616,
 22541,
 22688,
 36852,
 22385,
 35323,
 25177,
 36432,
 25322,
 22606,
 22509,
 22469,
 19058,
 22582,
 22502,
 19605,
 22808,
 21277,
 22668,
 25221,
 22721,
 17896,
 24406,
 22506,
 22612,
 22487,
 25237,
 27897,
 24064,
 22430,
 22527,
 22783,
 22529,
 25242,
 22821,
 22563,
 27010,
 20011,
 22378,
 22449,
 21827,
 25439,
 18648,
 22583,
 22831,
 22701,
 20903,
 22680,
 36829,
 20563,
 22819,
 19069,
 22647,
 21448,
 20077,
 22679,
 22865,
 22439,
 21662,
 21383,
 25371,
 22634,
 22833,
 19353,
 22534,
 25090,
 18763,
 21155,
 18835,
 18808,
 21265,
 22791,
 25277,
 22800,
 22692,
 18878,
 20068,
 21508,
 22536,
 22482,
 22324,
 22568,
 22702,
 22653,
 25231,
 36772,
 23778,
 18651,
 22653,
 34240,
 18669,
 18728,
 25260,
 20626,
 22688,
 22526,
 19516,
 22767,
 25000,
 19543,
 22764,
 36842,
 36376,
 19860,
 36403,
 22129,
 21213,
 18658,
 36615,
 22727,
 36246,
 25186,
 36424,
 22183,
 22562,
 17573,
 20676,
 21661,
 19290,
 22559,
 22648,
 20333,
 21684,
 21728,
 21116,
 22655,
 22749,
 21461,
 25334,
 36563,
 21812,
 25055,
 22469,
 25078,
 18825,
 22601,
 22714,
 20263,
 18880,
 24989,
 22511,
 36963,
 20404,
 22785,
 22449,
 22732,
 21276,
 25238,
 22795,
 36350,
 21824,
 16386,
 22245,
 36687,
 27699,
 22203,
 24899,
 36718,
 36655,
 22275,
 22115,
 36829,
 22430,
 26226,
 19315,
 25193,
 22449,
 36456,
 25199,
 19220,
 36892,
 22330,
 21374,
 22517,
 22526,
 20226,
 22395,
 18669,
 36341,
 22796,
 22383,
 25103,
 19436,
 36303,
 22222,
 18763,
 36265,
 36492,
 36406,
 22407,
 22675,
 22641,
 25141,
 22670,
 18871,
 22532,
 22206,
 22536,
 22532,
 22523,
 22384,
 20981,
 22752,
 22698,
 21492,
 19024,
 21261,
 21390,
 22575,
 18251,
 22516,
 22730,
 19005,
 16198,
 21890,
 19463,
 22601,
 22719,
 22551,
 18789,
 22420,
 22694,
 22482,
 24401,
 22744,
 20344]

In [16]:
X_train["PR_Seq"] = PR_train
X_train["RT_Seq"] = RT_train
X_test["PR_Seq"] = pr_test
X_test["RT_Seq"] = RT_test

In [17]:
X_train=X_train.drop(["PR Seq","RT Seq"],axis=1)

In [18]:
X_test=X_test.drop(["PR Seq","RT Seq"],axis=1)

In [19]:
X_test

           VL-t0  CD4-t0  PR_Seq  RT_Seq
PatientID
1           5.60      69    5623   36126
2           5.30     119    5645   36270
3           5.70      41    6068   22432
4           5.20      48    6057   36854
5           5.50     311    6052   22557
...          ...     ...     ...     ...
688         5.30     366    7295   18921
689         4.90     151    7230   36930
690         4.90     411    7301   21778
691         4.50     268    7275   22069
692         5.25     239    7292   21354

[692 rows x 4 columns]

In [20]:
y_test

PatientID
1      H
2      H
3      H
4      H
5      H
      ..
688    H
689    H
690    H
691    H
692    H
Name: Resp, Length: 692, dtype: object

In [21]:
model = LogisticRegression()

In [22]:
model.fit(X_train,y_train)

LogisticRegression()

In [23]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,y_train)

In [24]:
training_data_accuracy

0.8076086956521739

In [25]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,y_test)

TypeError: Labels in y_true and y_pred should be of the same type. Got y_true=[0 1] and y_pred=['H']. Make sure that the predictions provided by the classifier coincides with the true labels.

In [ ]:
test_data_accuracy

In [ ]:
input_data = (5.25,239,7292,21354)
# changing the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the np array as we are prediction for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)


if (prediction==1):
    print('The person has a HIV')
else:
    print('The person does not have a HIV')

In [ ]:
import seaborn as sns

In [ ]:
sns.pairplot(training_data)